version: "3.7"

services:
  mqtt_broker:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/:ro
    ports:
      - "1883:1883"
      - "9001:9001"

  iot_data_generator:
    build: ./iot_data_generator
    environment:
      - MQTT_HOST=mqtt_broker
      - MQTT_PORT=1883
      - MQTT_TOPIC=sensors
      - INTERVAL_MS=1000
      - LOGGING_LEVEL=20
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mqtt_broker
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  postgres_data:
  airflow_data:
